---
fail_fast: false
minimum_pre_commit_version: "2.6.0"
repos:
  -
    repo: https://github.com/tonynv/pre-commit-configs
    # To update run:
    # pre-commit autoupdate --freeze
    rev: 73c7f911d489eb85b1c8466f43f6dee4d533476d   # frozen: v1.3.2
    hooks:
      - id: aws-ia-highpoint-hook
