---
fail_fast: false
minimum_pre_commit_version: "2.6.0"
repos:
  -
    repo: https://github.com/tonynv/pre-commit-configs
    # To update run:
    # pre-commit autoupdate --freeze
    rev: b0e8a7e3223fd9f3d636be50a538d38de86d73b5  # frozen: v1.3.2
    hooks:
      - id: aws-ia-highpoint-hook
